--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.689.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 07.12.2021 15:03:30
-- Server version: 8.0.27
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE `туристическое бюро`;

--
-- Drop table `заказ путевок`
--
DROP TABLE IF EXISTS `заказ путевок`;

--
-- Drop table `категория`
--
DROP TABLE IF EXISTS категория;

--
-- Drop table `клиенты`
--
DROP TABLE IF EXISTS клиенты;

--
-- Drop table `название маршрута`
--
DROP TABLE IF EXISTS `название маршрута`;

--
-- Drop table `цена`
--
DROP TABLE IF EXISTS цена;

--
-- Set default database
--
USE `туристическое бюро`;

--
-- Create table `цена`
--
CREATE TABLE цена (
  `стоимость одного дня проживания` int DEFAULT NULL,
  `стоимость проезда` int DEFAULT NULL,
  `количество путевок` int DEFAULT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `название маршрута`
--
CREATE TABLE `название маршрута` (
  `Кузьмоловский карьер` int DEFAULT NULL,
  `Пеший поход по Карелии` int DEFAULT NULL,
  ` Гора Крокодил` int DEFAULT NULL,
  `Чёрная сопка` int DEFAULT NULL,
  `Гора Тепсей` int DEFAULT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `клиенты`
--
CREATE TABLE клиенты (
  `код клиента` int DEFAULT NULL,
  фамилия varchar(255) DEFAULT NULL,
  имя tinytext DEFAULT NULL,
  отчество tinytext DEFAULT NULL,
  адрес tinytext DEFAULT NULL,
  телефон int DEFAULT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `категория`
--
CREATE TABLE категория (
  отдых varchar(255) DEFAULT NULL,
  туризм varchar(255) DEFAULT NULL,
  лечение varchar(255) DEFAULT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `заказ путевок`
--
CREATE TABLE `заказ путевок` (
  `маршрут, дата начала` date DEFAULT NULL,
  `количество дней` int DEFAULT NULL,
  `проезд (самостоятельно/ нет)` tinytext DEFAULT NULL,
  `код клиента` int DEFAULT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

-- 
-- Dumping data for table цена
--
INSERT INTO цена VALUES
(1000, 5000, 150);

-- 
-- Dumping data for table `название маршрута`
--
INSERT INTO `название маршрута` VALUES
(10000, 1000, 2000, 1000, 500);

-- 
-- Dumping data for table клиенты
--
INSERT INTO клиенты VALUES
(1, 'Вольский', 'Дмитрий', 'Кузьмич', 'г Москва', 8992),
(2, 'Мышкин', 'гена', 'сергеевич', 'г Кирс', 82436),
(2, 'Мышкин', 'гена', 'сергеевич', 'г Кирс', 82436),
(2, 'Мышкин', 'гена', 'сергеевич', 'г Кирс', 82436),
(2, 'Мышкин', 'гена', 'сергеевич', 'г Кирс', 82436);

-- 
-- Dumping data for table категория
--
INSERT INTO категория VALUES
('да', 'нет', 'нет'),
('да', 'да', 'да'),
('да', 'да', 'да'),
('да', 'да', 'да'),
('нет', 'да', 'нет');

-- 
-- Dumping data for table `заказ путевок`
--
INSERT INTO `заказ путевок` VALUES
('2021-12-01', 100, 'нет', 1),
('2021-12-10', 50, 'да', 4),
('2021-12-10', 50, 'да', 4),
('2021-12-10', 50, 'да', 4),
('2021-12-18', 43, 'нет', 1);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;